Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: customer.functions.CreateCustomer
      CodeUri: /Users/daniil/Desktop/customerAPI_app/CustomerApi
      Runtime: java8.al2
      Architectures:
        - x86_64